defaultDataset: ga4_reporting
defaultLocation: US
defaultProject: ibqml-hackathon-noodles
vars: 
    DESTINATION_DATASET: ga4_reporting
    SOURCE_DATASET: noodles_ga4_data
    SOURCE_PROJECT: ibqml-hackathon-noodles
    SOURCE_TABLE_PREFIX: events_
    ENVIRONMENT: prod  
    HAS_ECOMMERCE: 'true'
